### ISSUE TITLE
[Bug]: keyboard wont show up on cover

### ISSUE THREAD

**Issue by HoneybeeMel** [SamSprung/SamSprung-TooIME#6]
### Issue Description

Keyboard wont show up on cover screen automatically when i try to use it. I have to switch to SamSprung keyboard before flipping my phone shut to use the keyboard otherwise it wont automatically open up on the cover screen. Please fix it. 

### Logcat Output

```shell
SamsprungKeyboardBug
```

### Wiki Confirmation

- [X] I have read and understood the current wiki

**Comment by AbandonedCart** [comment]
The keyboard should not be set as default or selected. Enabling accessibility handles the transition.

**Comment by AbandonedCart** [comment]
Also, circumventing the log requirement when the app provides the log makes it extremely difficult to verify there isn't a crash.

**Comment by AbandonedCart** [comment]
> ```shell
> SamsprungKeyboardBug
> ```

You wrote that, correct? You are demanding help, but you did make a conscious effort to make sure I couldn't help you.

**Comment by HoneybeeMel** [comment]
You've been repeating the same thing. I never even set the keyboard as
default for once and it sometimes doesn't show up on cover screen which
means the app needs more developer time. I've been asking you to take these
as feedbacks but you're responding to me so passive aggressively. What kind
of developer team is this? You should simply thank, consider it a feedback
and try to look into the issues users have come across. By the way, thanks
now the app display has been fixed after the last update i got today. I'm
not saying the keyboard never works, it does work and show up on the cover
but just "sometimes" it disappears. That's all. Just take it as a feedback.

**Comment by AbandonedCart** [comment]
I repeated (once) that a log is required because that is literally the only thing necessary to solve the issue.

Please keep in mind that we do not allow trolling. If you are going to continue making false accusations, you will be banned.

**Comment by HoneybeeMel** [comment]
I'm not even trolling. Does this look trolling to you??? Why are you this
passive aggressive??? I'm trying to give my feedback which is the fact that
keyboard does not always show up on the cover screen! Take it as it is and
simply thank. Jesus.
I've tried to report this issue with screenshots and you did not help at
all. The app can have flaws, hence why it still is under development. Can't
you just say "oh okay, our developer team will look into it. thanks"???
Because i have never seen this reaction before from ANY developer team. You
should take my e mail as a user feedback instead of denying the fact that
there's a problem and threatening a user by telling them they'll be banned
because they are trying to give a simple feedback? If you don't want
feedbacks, then why put this app on Play Store??

**Comment by AbandonedCart** [comment]
There are no screenshots and your "feedback" is insulting, not helpful. You can either try to provide enough information to resolve your issue or simply stop making comments. This is your final warning.
